#!/usr/bin/env python3
"""Standalone parity harness: native flowchart renderer vs. the vendored Go
binary, for a curated set of representative mermaid flowchart sources.

Not a pytest test and not imported by the test suite — the corpus tests must
not depend on the vendored ``mermaid-ascii`` binary being present on disk.
Run this once (locally, wherever the vendored binary for the host platform
exists) to (re)generate the side-by-side comparison artifact:

    .venv/bin/python scripts/mermaid_flow_parity.py

Invokes the Go binary exactly the way termrender's real dispatch path does
(``mermaid.py::_render_via_binary``): run ``preprocess_mermaid_for_ascii``
(flowchart shape normalization) on the source, shell out to
``mermaid_ascii_bin()`` with ``-f - -y 1``, and undo its Latin-1
double-encoding via ``fix_mermaid_encoding`` — so the comparison is fair
(same preprocessing termrender actually applies before falling back to the
binary today).
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from termrender._mermaid_bin import mermaid_ascii_bin
from termrender.renderers.mermaid import fix_mermaid_encoding, preprocess_mermaid_for_ascii
from termrender.renderers.mermaid_flow import render_flowchart

OUTPUT_PATH = Path(
    "/Users/silasrhyneer/.crouter/canvas/nodes/mr9swads-0f62d05c/context/flow-parity-sample.md"
)

WIDTH = 60

CASES: list[tuple[str, str]] = [
    (
        "Simple forward DAG",
        "graph TD\nA-->B\nA-->C\n",
    ),
    (
        "Multi-parent DAG",
        "graph TD\nA-->C\nB-->C\n",
    ),
    (
        "Headless edge (`---`)",
        "graph TD\nA---B\n",
    ),
    (
        "Pipe-labeled edge",
        "graph TD\nA-->|hi|B\n",
    ),
    (
        "Inline-labeled edge",
        "graph TD\nA -- go now --> B\n",
    ),
    (
        "`&` fan-out",
        "graph TD\nA & B --> C & D\n",
    ),
    (
        "Non-rect shapes (diamond, circle, cylinder)",
        "graph TD\nA{Decision}-->B((Circle))\nB-->C[(DB)]\n",
    ),
    (
        "LR direction",
        "graph LR\nA-->B\nA-->C\n",
    ),
    (
        "Subgraph frame",
        "graph TD\nsubgraph zone[Zone]\nA-->B\nend\n",
    ),
    (
        "Plain 3-cycle (no label)",
        "graph TD\nA-->B\nB-->C\nC-->A\n",
    ),
    (
        "Self-loop (Go binary PANICS: index out of range in drawLine)",
        "graph TD\nA-->A\n",
    ),
    (
        "Cycle with a LABELED back-edge (Go binary mis-parses the label as "
        "a phantom node — wrong topology; this is the case the requirements "
        "doc calls out as the one the Go binary cannot handle)",
        "graph TD\nA-->B\nB-->C\nC-->|retry|A\n",
    ),
    (
        "Same labeled-back-edge cycle, spaced arrows (Go binary still "
        "fabricates a phantom 4th node '|retry| A' instead of a back-edge "
        "into A — the label-parsing bug is not a whitespace quirk)",
        "graph TD\nA --> B\nB --> C\nC --> |retry| A\n",
    ),
    (
        "Simple forward DAG, spaced arrows (Go binary's own preferred "
        "form — included so the unspaced cases above are judged fairly "
        "against Go's best case, not just its worst case)",
        "graph TD\nA --> B\nA --> C\n",
    ),
]


def render_via_go_binary(source: str) -> tuple[str, bool]:
    """Return (rendered_text, panicked). Mirrors mermaid.py::_render_via_binary
    but surfaces panic/failure explicitly instead of silently echoing source
    (the harness wants to *show* the failure, not hide it)."""
    try:
        result = subprocess.run(
            [mermaid_ascii_bin(), "-f", "-", "-y", "1"],
            input=preprocess_mermaid_for_ascii(source),
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError) as exc:
        return f"[harness error invoking binary: {exc}]", True

    if result.returncode != 0:
        stderr_tail = "\n".join(result.stderr.strip().splitlines()[:4])
        return f"PANIC (exit {result.returncode}):\n{stderr_tail}", True

    return fix_mermaid_encoding(result.stdout), False


def main() -> None:
    sections: list[str] = [
        "# Native flowchart renderer vs. Go `mermaid-ascii` — parity sample",
        "",
        "Generated by `scripts/mermaid_flow_parity.py`. The Go binary is",
        "invoked exactly the way termrender's real dispatch path does today",
        "(`mermaid.py::_render_via_binary`): flowchart shape normalization via",
        "`preprocess_mermaid_for_ascii`, then `mermaid-ascii -f - -y 1`, then",
        "`fix_mermaid_encoding` on the output.",
        "",
    ]

    for title, source in CASES:
        go_text, panicked = render_via_go_binary(source)
        our_lines = render_flowchart(source, WIDTH)
        our_text = "\n".join(our_lines)

        sections.append(f"## {title}")
        sections.append("")
        sections.append("Mermaid source:")
        sections.append("```")
        sections.append(source.rstrip("\n"))
        sections.append("```")
        sections.append("")
        sections.append(f"Go binary output{' (PANIC/failure)' if panicked else ''}:")
        sections.append("```")
        sections.append(go_text if go_text.strip() else "(empty)")
        sections.append("```")
        sections.append("")
        sections.append("Native `render_flowchart` output:")
        sections.append("```")
        sections.append(our_text if our_text.strip() else "(empty)")
        sections.append("```")
        sections.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(sections) + "\n")
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
